### ISSUE TITLE
Finding "fixme" lints in Rubocop.yml

### ISSUE THREAD

**Issue by Mange** [codeclimate/codeclimate-fixme#15]
We have a `.rubocop.yml` file committed to the repo with the following config included:

```yml
Style/CommentAnnotation:
  Description: Checks formatting of special comments (TODO, FIXME, OPTIMIZE, HACK,
    REVIEW).
  StyleGuide: https://github.com/bbatsov/ruby-style-guide#annotate-keywords
  Enabled: false
  Keywords:
  - TODO
  - FIXME
  - OPTIMIZE
  - HACK
  - REVIEW
```

These are all detected as problems, but they shouldn't be IMO.
