### ISSUE TITLE
Allow configuring of strings

### ISSUE THREAD

**Issue by michaelmior** [codeclimate/codeclimate-fixme#20]
It would be nice if I could specify what strings this should use. For example, I might not care about TODOs or I may have some other string I'd like to alert on.

**Comment by ABaldwinHunter** [comment]
@michaelmior Thanks for the feedback. This is a great suggestion that we've considered implementing. I'm going to tag this issue as `enhancement` and make sure it's on our roadmap.

**Comment by ABaldwinHunter** [comment]
@michaelmior Thanks for your comment. We added this feature today!

https://github.com/codeclimate/codeclimate-fixme/commit/2d9e61b33ac842f678973ff4d17dd2da1444dbe8

You can now specify custom, case-sensitive strings in your `.codeclimate.yml`

```
engines:
  fixme:
    enabled: true
    config:
       strings:
       - APOCALYPSE
      - WIP
      - FIXME
```

Note, that for now the `.codeclimate.yml` file is not automatically excluded from analysis, so you may want to add it to `exclude_paths` to avoid false positives.

Closing this request for now.

Cheers,
Ashley
