### ISSUE TITLE
.rubocop.yml issue in PHP project??

### ISSUE THREAD

**Issue by bourdeau** [codeclimate/codeclimate-fixme#29]
Hi there,

I had no idea where to report this so I came here.

I've a PHP project that use Codeclimate and in my issues (https://codeclimate.com/github/bourdeau/jdhm-api/issues) I have a .rubocop.yml issue in TODO, FIXME and HACK.

but there is no such file on my repository... so I guess it has something to do with codeclimate-rubocop which has a .rubocop.yml no?

You help is welcome on this! Thanks!

**Comment by ABaldwinHunter** [comment]
Greetings @bourdeau! Thanks for the report.

We recently updated the way Code Climate generates engine-specific configs in our hosted analysis, including for RuboCop. Since your repository had ruby code but no .rubocop.yml, we auto-generated a `.rubocop.yml` config file to analyze your ruby code.

Update to remove the fixme triggers from our default `.rubocop.yml` as a first step is pending [here](https://github.com/codeclimate/codeclimate/pull/352)

**Comment by bourdeau** [comment]
Dear Ashley,

Thanks a lot for your quick reply (very impressive!! :+1: ). Yes I do use Capifony (a Capistrano fork) for deploys.

Okay so nothing to worry about by my side?

Have a nice day.

**Comment by ABaldwinHunter** [comment]
Nope you should be set! We're releasing the new Code Climate version today.

In the meantime, feel free to commit a `.codeclimate.yml` file with whatever engines you need. Perhaps

```
engines:
  phpmd:
    enabled: true
  phpcodesniffer:
    enabled: true
  fixme:
    enabled: true
  rubocop:
    enabled: false
exclude_paths:
- bin/
ratings:
  paths:
  - "**.php"
```
That can also serve as a temporary workaround to avoid the .rubocop.yml issues bug.

Thanks for alerting us!

Going to close this issue for now, but please feel free to reopen if anything comes up.
