### ISSUE TITLE
Case Question - Please add more info in the DOCs

### ISSUE THREAD

**Issue by intervalia** [codeclimate/codeclimate-fixme#52]
I inherited a project with the following:

```
  fixme:
    enabled: true
    config:
      strings:
      - FIXME
      - TODO
      - ToDo
      - Todo
      - todo
      - TO-DO
      - To-Do
      - HACK
      - Hack
      - hack
      - HERE BE DRAGONS
      - Here Be Dragons
```

My question is how does `fixme` handle case? Do I need all of the above or can I reduce it to the following:

```
  fixme:
    enabled: true
    config:
      strings:
      - FIXME
      - TODO
      - TO-DO
      - HACK
      - HERE BE DRAGONS
```

Also can you allow some level of `regex` so I can do the following:

```
  fixme:
    enabled: true
    config:
      strings:
      - FIX[-\s]*ME
      - TO[-\s]*DO
      - HACK
      - HERE[-\s]*BE[-\s]*DRAGONS
```

Thanks!!
